[package]
name = "bevy_ss_anim"
version = "0.1.0"
edition = "2021"
authors = ["lemz"]
keywords = ["bevy", "sparrow", "sprite-sheet", "ss", "sprite", "2d", "animation", "game", "engine", "asset", "system", "xml"]
description = "Animated-Sprite Using Sparrow-V2 Adobe Animate Sprite Sheets"
categories = ["game-development"]


[dependencies]
bevy = {version = "0.11.2", default-features = false, features = ["bevy_asset", "bevy_sprite"]}

serde = "1.0.188"
serde-xml-rs = "0.6.0"
